const mongoose = require("mongoose")

const ProductSchema = new mongoose.Schema(
    {
        seller:{
          type:mongoose.Schema.Types.ObjectId,
          ref:'Seller',
          required:true
        },
        Influencer:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Influencer',
          },
        title:{  
            type:String,
        },
        desc:{
            type:String,
        },
        productDetail:{
            type:Array,
        },
        img:{
            type:[],
        },
        imgKey:{
            type:[],
        },
        video:{
            type:[],
        },
        categories:{
            type:String,
            
        },
        Liquid_Type:{
            type:String
        },
        subcategories:{
            type:String,
           
        },
        Publisher:{
            type:String
        },
        color:{
            type:[],
        },
        Language:{
            type:String
        },
        Item_Weight:{
            type:String
        },
        brand:{
            type:String,
        },
        Material:{
            type:String
        },
        size:{
            type:[],
        },
        Date_First_Available:{
            type:String
        },
        Manufacturer:{
            type:String,
        },
        ASIN :{
            type:String,
        },
        Item_model_number:{
            type:String
        }, 
        Product_Dimensions:{
            type:String
        },
        Skin_Type:{
            type:String
        },
        Skin_Tone:{
            type:String
        },
        Age_Range:{
            type:String
        },
        Product_Benefits:{
            type:String
        },
        Hair_Type:{
            type:String
        },
        Material_Type_Free:{
            type:String
        },
       
        Scent:{
            type:String
        },
        Liquid_Volume:{
            type:String
        },
        Texture:{
            type:String
        },
       
        Country_of_origin:{
            type:String
        }, 
        Item_Weight:{
            type:String
        },
        Hair_Concerns:{
            type:String
        },
        Hair_Care_Benefits:{
            type:String
        },
        price:{
            type:Number,
            // required:true
        },
        ratings:{
            type:Number,
            default:0
        },
        Stock:{
            type:Number,
            required:[true , "Please Enter product Stock"],
            default:1,
        },
        numOfReviews:{
            type:Number,
            default:0
        },
        reviews:[
            {
                user:{
                    type:mongoose.Schema.ObjectId,
                    ref:'User',
                    required:true
                },
                username:{
                    type:String,
                },
                rating:{
                    type:Number,
                    required:true
                },
                comment:{
                    type:String,
                }
            }
        ],
    }, {timestamps:true}
);

module.exports = mongoose.model("Product" , ProductSchema);